package autocode

type ServiceGroup struct {
	// Code generated by github.com/jefferygeng/yj/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	SupplierService
	FuelSupplierContactService
	AgreementService
	AirportService
	FuelCustomerService
	FuelCustomerContractService
	FuelCustomerContactService
	FuelCustomerEmailService
	CmsCategoryService
	CmsContentService
	ZnFlightService
	// Code generated by github.com/jefferygeng/yj/server End; DO NOT EDIT.
}
