package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	SupplierService
	FuelSupplierContactService
	AgreementService
	AirportService
	FuelCustomerService
	FuelCustomerContractService
	FuelCustomerContactService
	FuelCustomerEmailService
	CmsCategoryService
	CmsContentService
	ZnFlightService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
