package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	SupplierApi
	FuelSupplierContactApi
	AgreementApi
	AirportApi
	FuelCustomerApi
	FuelCustomerContractApi
	FuelCustomerContactApi
	FuelCustomerEmailApi
	CmsCategoryApi
	CmsContentApi
	ZnFlightApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
