package frontend

type RouterGroup struct {
	// Code generated by github.com/jefferygeng/yj/server Begin; DO NOT EDIT.
	SmsRouter
	SystemCfgRouter
	// Code generated by github.com/jefferygeng/yj/server End; DO NOT EDIT.
}
