package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	SupplierRouter
	FuelSupplierContactRouter
	AgreementRouter
	AirportRouter
	FuelCustomerRouter
	FuelCustomerContractRouter
	FuelCustomerContactRouter
	FuelCustomerEmailRouter
	CmsCategoryRouter
	CmsContentRouter
	ZnFlightRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
